//389_Find_the_Difference.h
//3ms	100.00%

/*
Total Accepted: 64362
Total Submissions: 125058
Instruction: LeetCode 389 - Find the Difference - [E]
Developer: lrushx
Process Time: May 01, 2017
*/


/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
 * s = "abcd"
t = "abcde"
Output:e
Explanation:
'e' is the letter that was added.
*/


//给2个字符串s,t，t为s乱排后加了一个字母，求多的那个字母
//2种方法：统计a~z的个数，s中的+，t中的-，看最后那个字母的个数是负数即可；另一种是先格子排序，再逐位比较，复杂度由排序决定
//第一种方法O(n)确实时间更短，有hash table的感觉



    char findTheDifference(string s, string t) {
        int len = s.size(),i;
        vector<int> c(26,0);
        for (i=0;i<len;i++){
            c[s[i]-'a']++;
            c[t[i]-'a']--;
        }
        c[t[len]-'a']--;
        for (i=0;i<26;i++)
            if (c[i] < 0) return 'a'+i;
    }


        
    char findTheDifference(string s, string t) {
        int len = s.size(),i;
        sort(s.begin(),s.end());
        sort(t.begin(),t.end());
        for (i=0;i<len;i++)
            if (s[i] != t[i]) return t[i];
        return t[len];
    }