.PHONY: clean All

All:
	@echo "----------Building project:[ LeetCode - Debug ]----------"
	@cd "LeetCode" && "$(MAKE)" -f  "LeetCode.mk"
clean:
	@echo "----------Cleaning project:[ LeetCode - Debug ]----------"
	@cd "LeetCode" && "$(MAKE)" -f  "LeetCode.mk" clean
